/** \file tag_TFSFFaces.c
  * Function to read \b [TFSF: open faces] tag parameters from config file and prepare config file for \b core.out (main calculation module).
  *
  * To see what 'Total Field/Scattered Field" interface is, please consult documentation for main calculation
  * module (see em_TFSF.c file documentation) or short description at tag_TFSF.c. This tag is used to remove sources from certain face(s)
  * in \b play mode. If the purpose of this sources was to cancel outgoing solution (like in case of the generated laser pulse going through
  * interfaced region) then this tag helps to let recorded pulse go out.
  *
  * Example of the config file entry is
    <pre>
    [TFSF: open faces]
    > xMin		Opens xMin face.
    > zMax		Opens zMax face.

      TF/SF stands for Total Field/Scattered Field interface.
      Optional face names are 'xMin', 'xMax', 'yMin', 'yMax', 'zMin', 'zMax'.
    </pre>
  *
  * \todo Link on main documentation page for \b em_TFSF.c.
  */

#include <stdio.h>
#include <string.h>

#include "log.h"
#include "misc_cfgReader.h"
#include "misc_parameters.h"

// ---------------------------------------------------------------------------
/// Structure for simplified search.
// ---------------------------------------------------------------------------
struct opening_s
{
  const char *name;			///< Symbolic name of the face.
  int opened;				///< Opened mark (\b 1 means face is removed as a play-source).
};

static struct opening_s faces[6] = { {"xMin", 0}, {"xMax", 0}, {"yMin", 0}, {"yMax", 0}, {"zMin", 0}, {"zMax", 0} };

// ---------------------------------------------------------------------------
/// Tag entry point.
// ---------------------------------------------------------------------------
void
tag_TFSFOpenFaces (FILE *fp)
{
  static int first = 1;

  if (!first)														// Ensures uniqness of the call.
    SAY_WARNING ("tag [TFSF: open faces] is used twice");
  first = 0;

  const char *word = NULL;
  say ("tag_TFSFOpenFaces: ");
  while (cfg_isOption (fp))												// Gets all options.
  {
    word = cfg_readOptWord (fp);

    int f = 0;
    for ( ; f < 6 ; ++f)
      if (!strcmp (faces[f].name, word))
        break;

    ENSURE (f < 6, "word '%s' is not a valid option here", word);

    faces[f].opened = 1;
    say ("  - removing face %s ...", faces[f].name);
  }

  if (!word)
    say ("  Tag is called but no faces marked to open.");

  if (cpu_here)														// Master will update all files.
    return;

  FILE *file = cfg_open (".EM_sources/TFSF/openFaces.cfg", "wt", __func__);
  for (int f = 0 ; f < 6 ; ++f)
    fprintf (file, "@ %d        state of %s (0 - engaged, 1 - opened/removed)\n", faces[f].opened, faces[f].name);
  fprintf (file, "\n\n  This file is automatically generated by setup.out (tag [TFSF: open faces]).\n");
  fclose (file);
}
