/** \file frame.h
  * Dimensionality (1D/2D/3D) configuration file.
  * File is automatically regenerated by [tag_mesh] handler.
  */

#ifndef mc_have_x

#define  mc_have_x   1
#define  mc_have_y   1
#define  mc_have_z   1

#endif
